/** Generated by `npm run generate-licenses-data`, one entry per dependency. */
declare const licenses: Record<
  string,
  {
    name: string
    version: string
    licenses: string
    copyright: string
    repository: string
  }
>
export default licenses
